# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from blackboard/TaskMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class TaskMsg(genpy.Message):
  _md5sum = "36aacfc4fa43201ce4e714ef4c2d80ab"
  _type = "blackboard/TaskMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 taskId
int16 priority
int16 taskType
int16 payload
int16 taskState
float32 cost
float32 energyCost
int16 robotId
geometry_msgs/Pose[] pose
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['taskId','priority','taskType','payload','taskState','cost','energyCost','robotId','pose']
  _slot_types = ['int16','int16','int16','int16','int16','float32','float32','int16','geometry_msgs/Pose[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       taskId,priority,taskType,payload,taskState,cost,energyCost,robotId,pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TaskMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.taskId is None:
        self.taskId = 0
      if self.priority is None:
        self.priority = 0
      if self.taskType is None:
        self.taskType = 0
      if self.payload is None:
        self.payload = 0
      if self.taskState is None:
        self.taskState = 0
      if self.cost is None:
        self.cost = 0.
      if self.energyCost is None:
        self.energyCost = 0.
      if self.robotId is None:
        self.robotId = 0
      if self.pose is None:
        self.pose = []
    else:
      self.taskId = 0
      self.priority = 0
      self.taskType = 0
      self.payload = 0
      self.taskState = 0
      self.cost = 0.
      self.energyCost = 0.
      self.robotId = 0
      self.pose = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5h2fh().pack(_x.taskId, _x.priority, _x.taskType, _x.payload, _x.taskState, _x.cost, _x.energyCost, _x.robotId))
      length = len(self.pose)
      buff.write(_struct_I.pack(length))
      for val1 in self.pose:
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.orientation
        _x = _v2
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = None
      end = 0
      _x = self
      start = end
      end += 20
      (_x.taskId, _x.priority, _x.taskType, _x.payload, _x.taskState, _x.cost, _x.energyCost, _x.robotId,) = _get_struct_5h2fh().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pose = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v3 = val1.position
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v4 = val1.orientation
        _x = _v4
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.pose.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5h2fh().pack(_x.taskId, _x.priority, _x.taskType, _x.payload, _x.taskState, _x.cost, _x.energyCost, _x.robotId))
      length = len(self.pose)
      buff.write(_struct_I.pack(length))
      for val1 in self.pose:
        _v5 = val1.position
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = val1.orientation
        _x = _v6
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = None
      end = 0
      _x = self
      start = end
      end += 20
      (_x.taskId, _x.priority, _x.taskType, _x.payload, _x.taskState, _x.cost, _x.energyCost, _x.robotId,) = _get_struct_5h2fh().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pose = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v7 = val1.position
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.orientation
        _x = _v8
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.pose.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_5h2fh = None
def _get_struct_5h2fh():
    global _struct_5h2fh
    if _struct_5h2fh is None:
        _struct_5h2fh = struct.Struct("<5h2fh")
    return _struct_5h2fh
