# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from blackboard/TaskCost.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TaskCost(genpy.Message):
  _md5sum = "0f44cd155759633dbc2acfa15e81bd1c"
  _type = "blackboard/TaskCost"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 taskId
float32 taskCost
int16 robotId
float32 energyCost"""
  __slots__ = ['taskId','taskCost','robotId','energyCost']
  _slot_types = ['int16','float32','int16','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       taskId,taskCost,robotId,energyCost

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TaskCost, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.taskId is None:
        self.taskId = 0
      if self.taskCost is None:
        self.taskCost = 0.
      if self.robotId is None:
        self.robotId = 0
      if self.energyCost is None:
        self.energyCost = 0.
    else:
      self.taskId = 0
      self.taskCost = 0.
      self.robotId = 0
      self.energyCost = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_hfhf().pack(_x.taskId, _x.taskCost, _x.robotId, _x.energyCost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.taskId, _x.taskCost, _x.robotId, _x.energyCost,) = _get_struct_hfhf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_hfhf().pack(_x.taskId, _x.taskCost, _x.robotId, _x.energyCost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.taskId, _x.taskCost, _x.robotId, _x.energyCost,) = _get_struct_hfhf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_hfhf = None
def _get_struct_hfhf():
    global _struct_hfhf
    if _struct_hfhf is None:
        _struct_hfhf = struct.Struct("<hfhf")
    return _struct_hfhf
